# Generated by Django 4.2.16 on 2024-11-21 15:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("glossary", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="term",
            name="full_term",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
