# Generated by Django 4.2.16 on 2024-11-23 08:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("glossary", "0002_term_full_term"),
    ]

    operations = [
        migrations.AddField(
            model_name="term",
            name="view_count",
            field=models.IntegerField(default=0),
        ),
    ]
